### ISSUE TITLE
Business Unit

### ISSUE THREAD

**Issue by usmankazi** [sapplica/sentrifugo#157]
not creating business unit
![business unit](https://user-images.githubusercontent.com/29498251/27250865-469ffdd2-5353-11e7-8ed7-97f21cf5c7da.png)

**Comment by sapplica** [comment]
Hi,

Kindly update any of the records in the Roles & Privileges. Go to: HR › User Management › Roles & Privileges.

Thank you!

**Comment by usmankazi** [comment]
I have checked that but i have HR role and i have full access all option were checked but still having issue 

Regards

**Comment by usmankazi** [comment]
once i upgrade the Application from 3.1.1 to 3.2 the problem was resolved, kindly check in your latest release

Regards
Usman

**Comment by usmankazi** [comment]
i have noted that its not work with php7, i recommand please follow the version recommanded by the team

**Comment by tarassh** [comment]
The problem still exists, 

The paginator does next query:

SELECT distinct(b.id) AS `id`, `b`.`isactive`, `b`.`unitcode`, `b`.`address1`, `b`.`unitname`, `b`.`unithead`, DATE_FORMAT(b.startdate,"%m/%d/%Y") AS `startdate`, `c`.`city`, `s`.`state`, `cn`.`country`, concat(tz.timezone," [",tz.timezone_abbr,"]") AS `timezone` FROM `main_businessunits` AS `b`
 LEFT JOIN `main_cities` AS `c` ON b.city=c.city_org_id
 LEFT JOIN `main_states` AS `s` ON  s.state_id_org = b.state
 LEFT JOIN `main_countries` AS `cn` ON  cn.country_id_org = b.country
 LEFT JOIN `main_timezone` AS `tz` ON b.timezone=tz.id and tz.isactive=1 WHERE ( b.isactive = 1 AND b.id <> 0 ) ORDER BY `b`.`modifieddate` DESC LIMIT 20

Error Code: 3065. Expression #1 of ORDER BY clause is not in SELECT list, references column 'sentrifugo.b.modifieddate' which is not in SELECT list; this is incompatible with DISTINCT


Maybe remove distinct.
